title: Aryan Kashyap
description: Final Project for AOS C111/C204 â€“ Water Potability Prediction Using Machine Learning
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-cayman
